# Generated by Django 6.1.1 on 2026-09-09 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('collaboration_type', models.CharField(choices=[('faculty_internship', 'Faculty Internship'), ('industrial_training', 'Industrial Training'), ('fdp', 'Faculty Development Program'), ('consultancy', 'Consultancy'), ('research_project', 'Research Project'), ('mentorship', 'Mentorship'), ('workshop', 'Workshop'), ('guest_lecture', 'Guest Lecture'), ('innovation_challenge', 'Innovation Challenge'), ('live_project', 'Live Industry Project')], max_length=30)),
                ('target_type', models.CharField(choices=[('faculty', 'Faculty'), ('institution', 'Institution')], max_length=20)),
                ('eligibility', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('hybrid', 'Hybrid')], default='online', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('skills_topics', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_requests', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='collaborations.collaborationopportunity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('opportunity', 'applicant'), name='unique_collaboration_request')],
            },
        ),
    ]
