# Generated by Django 6.1.1 on 2026-09-07 06:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('mode', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'On-site')], default='hybrid', max_length=10)),
                ('duration', models.CharField(default='3 months', max_length=50)),
                ('stipend', models.CharField(default='Unpaid', max_length=50)),
                ('min_cgpa', models.FloatField(default=6.0)),
                ('deadline', models.DateField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='accounts.industryprofile')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='internships', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=150)),
                ('experience_required', models.CharField(default='0-1 years', max_length=50)),
                ('salary', models.CharField(default='As per industry standards', max_length=50)),
                ('min_cgpa', models.FloatField(default=6.0)),
                ('deadline', models.DateField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.industryprofile')),
                ('required_skills', models.ManyToManyField(blank=True, related_name='jobs', to='skills.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('match_score', models.FloatField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('internship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.internship')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.job')),
            ],
        ),
        migrations.CreateModel(
            name='LearningProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('duration', models.CharField(default='4 weeks', max_length=50)),
                ('program_type', models.CharField(choices=[('course', 'Course'), ('certification', 'Certification'), ('workshop', 'Workshop'), ('mentorship', 'Mentorship')], default='course', max_length=20)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_programs', to='skills.skill')),
            ],
        ),
    ]
