# Generated by Django 6.1.1 on 2026-09-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_required_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningprogram',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
