# Generated by Django 6.1.1 on 2026-09-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='github_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
