# Generated by Django 6.1.1 on 2026-09-10 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('industry', 'Industry'), ('faculty', 'Faculty'), ('admin', 'Institution')], default='student', max_length=20),
        ),
    ]
